spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/node_dev?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

    redis:
        host: 127.0.0.1
        port: 6379

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level: debug
